name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MONGODB_URI: mongodb://localhost:27017

jobs:
  build:

    runs-on: ubuntu-latest
    services: 
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: List directory structure
      run: ls -la
    - name: Check subdirectories
      run: find . -type d -maxdepth 3 | sort
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: rust-server101/actix-server
    - name: Run tests
      run: cargo test --verbose
      working-directory: rust-server101/actix-server
