name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List directory structure
      run: ls -la
    - name: Check subdirectories
      run: find . -type d -maxdepth 3 | sort
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: rust-server101/actix-server
    - name: Run tests
      run: cargo test --verbose
      working-directory: rust-server101/actix-server
